### ISSUE TITLE
errore in install packages 

### ISSUE THREAD

**Issue by Yassin6up** [VNOpenAI/pushup-counter-app#4]
`  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      Traceback (most recent call last):
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-ax7lkcmu\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-ax7lkcmu\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-ax7lkcmu\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Temp\pip-build-env-ax7lkcmu\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
      AssertionError: Could not find "cmake" executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by PanduZidni** [comment]
The error you are encountering indicates that the "cmake" software was not found. "cmake" is a tool that is often used in the process of compiling and building several Python packages. In this case, the package you are trying to install requires "cmake" to build wheel (the distribution file).

To solve this problem, you need to make sure that "cmake" is installed and accessible through your Python environment. Here are some steps you can try:

Make sure you have "cmake" installed on your system. You can visit the official website of "cmake" (https://cmake.org/download/) to download and install the latest version according to your operating system. Make sure "cmake" is listed in the system's PATH variable.

If you have installed "cmake" and still receive the same error, make sure that your system PATH is configured correctly. Check if the "cmake" installation directory is added to the PATH variable. To test this, open a terminal or command prompt and type "cmake" to see if the command is recognized.

If you are using a virtual environment (eg virtualenv or conda environment), make sure "cmake" is installed in it. Activate your virtual environment and make sure "cmake" is accessible from it.

Once you have confirmed that "cmake" is properly installed and accessible, try reinstalling the package causing the error. If the problem persists, please provide more information about which package you're trying to install, as well as the steps you performed previously, so that I can provide more detailed assistance.
